---
- name: Automate the setup of a web server on node2
  hosts: webserver
  become: true
  vars:
    - firewall_pkg: firewalld
    - firewall_svc: firewalld
    - web_pkg: httpd
    - web_svc: httpd
    - ssl_pkg: mod_ssl
    - web_root: /var/www/html

  tasks:
    - name: packages are installed
      ansible.builtin.dnf:
        name:
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"  
          - "{{ ssl_pkg }}"
        state: latest

    - name: Create the web content file 
      ansible.builtin.copy:
        content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4']['address'] }}) has been customized by Ansible."
        dest: "{{ web_root }}/index.html"

    - name: Enable and start the firewall service
      ansible.builtin.service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: yes

    - name: http service is allowed
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Enable and start the {{ web_svc }} service
      ansible.builtin.service:
        name: "{{ web_svc }}"
        state: started
        enabled: yes
     
- name: Test and verify the http access
  hosts: control
  connection: local
  become: true

  tasks:
    - name: Test http service and returned content
      ansible.builtin.uri:
        url: http://node2
        status_code: 200
        return_content: true
      register: content_result

    - name: Display the content of the register variable
      ansible.builtin.debug:
        msg: "{{ content_result }}"
   
  
